... warning: badref.inp: some points do not strictly dominate the reference point and they will be discarded
24
=== oneleft ===
... warning: badref.inp: some points do not strictly dominate the reference point and they will be discarded
8
=== emptyref ===
... warning: badref.inp: some points do not strictly dominate the reference point and they will be discarded
... error: none of the points strictly dominates the reference point
